/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rawconsole_RawConsole */

#ifndef _Included_rawconsole_RawConsole
#define _Included_rawconsole_RawConsole
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rawconsole_RawConsole
 * Method:    getRawKeyId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_rawconsole_RawConsole_getRawKeyId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
